fluidex/dingir-exchange

- .github/workflows/integration_test.yaml
This reverts commit 313ed4198800eb3c45d2cd071b05b9b5e7c4d1d8.
> Revert "chore(github): fix integration test (#17)"

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/restapi/errors.rs
- src/restapi/main.rs
- src/restapi/mock.rs
- src/restapi/tradingview.rs
- src/restapi/types.rs
These APIs are following [tradingview chart API](https://zlq4863947.gitbook.io/tradingview/3-shu-ju-bang-ding/udf).
> feat: add a mock kline impl

- .env
- config.yaml
- examples/js/client.mjs
- examples/js/config.mjs
- examples/js/stress.js
- examples/js/trade.js
- examples/js/util.mjs
- proto/exchange/matchengine.proto
- src/asset.rs
- src/controller.rs
- src/market.rs
- src/restapi/tradingview.rs
- src/server.rs
- src/sqlxextend.rs
1.  feat: add 'cancel all my orders on this market' api <https://github.com/Fluidex/dingir-exchange/issues/30>
2.  fix: decimal precision now works
3. config: change default ETH_BTC to ETH_USDT
4. make grpc output more readable
> feat: add 'cancel all my orders on this market' api

- Cargo.lock
- Cargo.toml
- src/asset.rs
- src/bin/restapi.rs
- src/controller.rs
- src/models.rs
- src/restapi/mod.rs
- src/restapi/personal_history.rs
- src/restapi/public_history.rs
- src/sqlxextend.rs
- src/utils.rs
1. order history api
2. batch insert will not ignore error now
3. some utility functions of date/time
> feat: add order history api

- src/bin/persistor.rs
- src/matchengine/controller.rs
- src/storage/database.rs
This resolve #56,
it also applied the commit <ab525>: as discussed in Fluidex#52, make is_block work like original code
> fix: fix try_acquire() error handling & is_block() for writers' capabilities

- examples/js/print_orders.js
- src/bin/persistor.rs
- src/matchengine/market.rs
- src/message/persist.rs
- src/restapi/public_history.rs
- src/restapi/types.rs
For issue 80:
Now persistor will check order messages received from kafka and only persist which have ordereventtype is FINISH 
For issue 82:
Trade_id included. Notice a rfc3339 time format include time zone and currently I just set it to UTC.
> fix: issue 80,82

- src/matchengine/market.rs
- src/matchengine/mod.rs
- src/storage/database.rs
- src/storage/sqlxextend.rs
- src/types/mod.rs
Add sleep(1s) for each failed inserting query
> fix tedious logging

- src/matchengine/persist.rs
Resolve the feature requirement #109: 
I simply constraint the max batching size to avoid expense too much memory (currently 10000, may be larger?)
> Features: persist use batch insert

- src/restapi/tradingview.rs
Any API in timescaledb jusst build a "nullable" column so they should be represented by Option<...> for the corresponding field in struct when querying by "query_as". In the function calling version of query_as, sqlx automatically convert the type if the passed struct using plain type when there is data avaliable but throw error when the api return null.
Macro version of query_as with compile-time verification will complain that but I had failed to put then in the verify code ...
This PR should fix the issue that ticker and history API would return failure when db is empty or no data could be selected.
> fix issue in ticker when no data avaliable

- .github/workflows/integration_test.yml
- examples/js/client.mjs
- examples/js/transfer.js
- proto/exchange/matchengine.proto
- src/matchengine/asset/balance_manager.rs
- src/matchengine/controller.rs
- src/matchengine/server.rs
Closes #99 
Adds an API `transfer` to support transfer asset to another account.
. Implements step-2.
> Implement feature: support transfer asset to another account inside exchange

- src/matchengine/asset/asset_manager.rs
> fix(matchengine): round up amount and price in commit order

- Cargo.lock
- Cargo.toml
> Update to use the master branch of fluidex-common

- Cargo.lock
- Cargo.toml
close https://github.com/Fluidex/dingir-exchange/issues/224
> build: bump prost-types version to 0.8.0

- .env
- Cargo.lock
- Cargo.toml
- src/bin/matchengine.rs
- src/bin/persistor.rs
- src/bin/restapi.rs
- src/bin/test_unifymessenger.rs
- src/matchengine/persist/state_save_load.rs
Closes #256 
Associates PR https://github.com/Fluidex/common-rs/pull/7
> Replace logger with feature `non-blocing-tracing` of `common-rs`

- src/matchengine/asset/update_controller.rs
- src/matchengine/controller.rs
- src/matchengine/market/mod.rs
- src/matchengine/persist/persistor.rs
- src/message/mod.rs
- src/message/producer.rs
> Produce deposit and withdraw messages to unify topic

- migrations/20210817060757_add_signature_to_internal_transfer.sql
- src/matchengine/controller.rs
- src/message/mod.rs
- src/message/persist.rs
- src/storage/models.rs
second task of issue https://github.com/fluidex/dingir-exchange/issues/270
> Add field signature to `InternalTx`

- examples/js/client.ts
- examples/js/tick.ts
Associates https://github.com/fluidex/rollup-state-manager/pull/171
> Update to multiple transfer msgs to script tick

- .github/workflows/integration-test.yml
- Cargo.lock
- Cargo.toml
- examples/js/client.ts
- examples/js/put_batch_orders.ts
- src/matchengine/controller.rs
- src/matchengine/server.rs
> feat: add `batch-order-put` API

- src/bin/openapi.rs
- src/lib.rs
- src/openapi/mod.rs
- src/openapi/user.rs
- src/storage/models.rs
Swagger JSON:
```
curl http://0.0.0.0:50054/api/spec
{"swagger":"2.0","definitions":{"AccountDesc":{"type":"object","properties":{"id":{"type":"integer","format":"int32"},"l1_address":{"type":"string"},"l2_pubkey":{"type":"string"}},"required":["id","l1_address","l2_pubkey"]}},"paths":{"/openapi/ping":{"get":{"responses":{}}},"/openapi/user/{l1addr_or_l2pubkey}":{"get":{"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/AccountDesc"}}}}}},"info":{"version":"","title":""}}
```
Common REST API：
```
curl -v http://0.0.0.0:50053/restapi/user/0x6286d0A2FC1d4C12a4ACc274018b401c68157Fdb
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 50053 (#0)
> GET /restapi/user/0x6286d0A2FC1d4C12a4ACc274018b401c68157Fdb HTTP/1.1
> Host: 0.0.0.0:50053
> …
```
> Add `get_user` to Open API

- src/bin/matchengine.rs
This should be helpful for debugging.
> Add PSQL connection string to connection failed error message

- migrations/20210514140412_account.sql
close https://github.com/fluidex/dingir-exchange/issues/247
> fix (db schema): use correct length for l1_address

- src/matchengine/controller.rs
- src/restapi/user.rs
Closes https://github.com/fluidex/dingir-exchange/issues/311
> Bug: Fix `l1-adress` and `l2-pubkey` to lower case

- src/storage/config.rs
close https://github.com/fluidex/dingir-exchange/issues/314
> fix: fix column_num mismatch in `persist_asset_to_db`

- config/restapi.yaml
- src/bin/restapi.rs
- src/restapi/config.rs
> Add `restapi` config file

- Cargo.lock
- Cargo.toml
- src/restapi/tradingview.rs
Reported from community.
Upgrade `actix-web` to `4.0.0-beta.12`.
> Upgrade `actix-web` with paperclip

- examples/js/package-lock.json
- examples/js/package.json
- examples/js/tests/tick_no_deploy.ts
- src/matchengine/controller.rs
+ The rounding of depositing balance use "Bankers Rounding” which may lead to a larger amount than user actually have deposited. And the amount would not be consistent with the data saved inside contracts for priority operations. So it should be changed into rounding to the ceil
+ For backend, replace tick.js with a similar script which do not assign or registry users. Because these actions should be done from L1 now
> Trivial update when inducing data avaliability

- Cargo.lock
- Cargo.toml
> Update with upstream paperclip
